repos:
  - repo: local
    hooks:
      - id: run-pylint
        name: Run Pylint
        entry: bash -c "pylint $(git ls-files '*.py')" 
        language: system
        pass_filenames: false
        stages: [commit]
      - id: run-pytest
        name: Run Pytest with Coverage
        entry: bash -c "pytest --cov=items_api --cov-fail-under=75 tests/"
        language: system
        pass_filenames: false
        stages: [commit]
