name: Python Lint, Test, and Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dependencies/requirements-dev.txt

    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Running tests with pytest and checking coverage
      run: |
        export DATABASE_URL=sqlite+aiosqlite:///test.db
        pytest --cov=items_api --cov-report=xml --cov-report=html --cov-fail-under=75 tests/

    - name: Clean up SQLite file
      run: rm -f test.db

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov
