name: Python Lint, Test, and Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dependencies/requirements-dev.txt

    - name: Analyzing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Running tests with pytest and checking coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html --cov-fail-under=75

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov
